### ISSUE TITLE
A possibility to NOT automap

### ISSUE THREAD

**Issue by rdkleine** [ArcadyIT/AutoMapper#2]
When mapping a large dto we'd like to ignore all properties which aren't mapped. 
So when we have a dto like
{
propa: 'a',
propb: 'b'
propc: 'c'
.....
propz: 'z'
}

And we just want to have as a result:
{
propa: 'a1234'
}

It would be much less code to just to create a mapping for propa and auto ignore b > z. Now I have to write ignore for b > z.

**Comment by loedeman** [comment]
Hi Ralf, thanks for the suggestion. My goal with AutoMapper in TypeScript has been to reflect the original AutoMapper implementation as closely as possible. The scenario you suggest is available as an extension to the original AutoMapper implementation (http://stackoverflow.com/questions/954480/automapper-ignore-the-rest). Since it is quite easy to implement in the TypeScript implementation, you may expect this one to be around pretty soon ;) ...

**Comment by rdkleine** [comment]
thanks :+1:
