### ISSUE TITLE
AssertMappings

### ISSUE THREAD

**Issue by runes83** [ArcadyIT/AutoMapper#4]
Does there exist a function to check if mappings are done similar to the .NET version?

This is very handy to know if all properties on an object have been mapped

**Comment by loedeman** [comment]
Not yet, but we are thinking about / planning for such a function. You should take in consideration though that nog evergreens is possible, since three is basically no typing in JavaScript. I will keep you posted on progress ;) . Should you have any ideas, those are most welcome ;) ...





On Fri, Oct 9, 2015 at 2:15 AM -0700, "Rune Synnevåg" <notifications@github.com<mailto:notifications@github.com>> wrote:


Does there exist a function to check if mappings are done similar to the .NET version?

This is very handy to know if all properties on an object have been mapped

-

**Comment by runes83** [comment]
Hello,

When you use typescript there is typings, and here it will make a lot of sense. Would be a very nice tool to have.

Regards
Rune

Fra: Bert Loedeman [mailto:notifications@github.com]
Sendt: fredag 9. oktober 2015 14:54
Til: ArcadyIT/AutoMapper <AutoMapper@noreply.github.com>
Kopi: Rune Synnevåg <rune.synnevaag@unipluss.no>
Emne: Re: [AutoMapper] AssertMappings (#4)

Not yet, but we are thinking about / planning for such a function. You should take in consideration though that nog evergreens is possible, since three is basically no typing in JavaScript. I will keep you posted on progress ;) . Should you have any ideas, those are most welcome ;) ...





On Fri, Oct 9, 2015 at 2:15 AM -0700, "Rune Synnevåg" <notifications@github.com<mailto:notifications@github.com<mailto:notifications@github.com%3cmailto:notifications@github.com>>> wrote:


Does there exist a function to check if mappings are done similar to the .NET version?

This is very handy to know if all properties on an object have been mapped

-

**Comment by loedeman** [comment]
I started working on a validation mechanism (automapper.assertConfigurationIsValid()). However, as I stated before, there is not a lot of typing at runtime in JavaScript. Currently, the maximum I seem to be able to reach is:

* Create a mapping configuration using class definitions instead of strings (possible in 1.4.0). Note that in order to get properties available on class initialization, you have to initialize them (e.g. prop: string = undefined;).
* Validate mapping using the assertConfigurationIsValid function. I have created a strictMode switch, because (at least for now) I am simply not able to test configurations not based on class definitions. Should you mix them, you could swith strictMode off to at least partially test your configuration.

Hope this helps ;) ! Cheers!

**Comment by loedeman** [comment]
Hi Rune, for now, I am closing this issue. I will leave the issue open for comments, should you have any comments on the currently available assertion possibilities, your remarks are most welcome ;) ...
